### ISSUE TITLE
Final Capstone Project: Car Rental

### ISSUE THREAD

**Issue by demix007** [demix007/CAR-RENTAL-BACKEND#14]
## Hello 👋🏼 ,

This is our final capstone project in Microverse. Our team consists of 3 individuals, namely:
     💠  @demix007 
     💠 @soulemanou-software 
     💠 @Nejjari001 

### Below is a screenshot of the  [Kanban board](https://github.com/users/demix007/projects/2) :

![Screenshot (81)](https://user-images.githubusercontent.com/35904766/228298855-55c5e5eb-794b-48af-8629-b5d3ae1fd3e3.png)

## Thank you 💯

**Comment by Meltrust** [comment]
Hi @demix007 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not include a screenshot of the kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi STUDENT_MENTION 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is not public.  I can't access it to review.

![image](https://user-images.githubusercontent.com/57421823/228312834-89611edf-fbf3-43d3-b348-7976c84610a7.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi @demix007,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!





Congratulations! 🎉 



## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by demix007** [comment]
## Hi @Meltrust 😎 ,

Thank you for reviewing and approving this PR. You are amazing 💯
